---
title: "Home"
---

## About

I'm a conlanger who creates artistic languages that I usually intend to be more or less naturalistic in nature. I also happen to be a linguist (PhD awarded 2021) and work predominantly in the fields of phonetics and phonology.

I've been constructing languages as a hobby since I was an undergrad and here you can find uploads of and links to some of my work. This currently includes some bits and pieces from [Kamya](kamya/index.qmd), [Xwere Gonom](xwere-gonom/index.qmd), [Sar̃ifa](sarifa/index.qmd) and [Anderiva](anderiva/index.qmd). My GitHub also hosts [Lexifer Plus](https://github.com/keras-saryan/lexifer-plus), a customised version of the word generator [Lexifer Online](https://lingweenie.org/conlang/lexifer-app.html).

## Contact

If you'd like to say hi, give me feedback on my work or get in touch for any other reason, you can do so by e-mail at `keras[dot]saryan[at]gmail[dot]com` or, if you prefer, I'm also on Reddit as [u/keras_saryan](https://www.reddit.com/user/keras_saryan) and on Discord as keras_saryan. You can find me on YouTube as [@keras_saryan](https://www.youtube.com/@keras_saryan) and on Twitch as [keras_saryan](https://www.twitch.tv/keras_saryan), albeit only as a viewer not a creator.

::: {.callout-note appearance="simple"}
Unless otherwise stated or permission is otherwise granted, all content posted here authored by me is published under a [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) licence.
:::
