---
title: "Anderiva"
---

Anderiva [ˌãⁿdɛɾɪˈβa] is a (mostly) head-final language spoken by a people living in a hilly humid subtropical forested area.

The language has a very small phonemic inventory (6 consonants, 3 oral vowels, 3 nasal vowels) but an extremely high degree of allophony (c. 40 consonants, 8 oral vowels, 6 nasal vowels). Nouns fall into one of four classes (= genders) and, though most adnominal modifiers are preposed, definite articles (homophonous with third-person pronouns) and demonstratives are postposed. Numerals, quantifiers and the indefinite article obligatorily take a suffixed classifier whose form is dependent on the modified/referent noun. Anderiva exhibits both clause chaining and switch reference in which medial verbs are conjugated only for same/different subject and simultaneity/sequentiality; final verbs are conjugated for person/number, tense/aspect and can be followed by various modal/evidential particles.

## Output

In October 2025, I gave a presentation entitled *Kut bero mi...* at [Kopikon II](https://kopikon.com/kopikon2/) in Edinburgh in which I used an original short story to showcase certain aspects of the language (slides [here](https://keras-saryan.github.io/kopikon-ii/), clipped video [here](https://www.youtube.com/watch?v=uXeZs-ofl4I) and full livestream [here](https://www.youtube.com/live/Vmyr10xHv3A?si=EkzrLEfhXemJjQFJ&t=3174)).

I used Anderiva throughout Lexember in 2025 and the full final PDF of the entries for each day can be found [here](../files/anderiva-lexember-2025.pdf).

In 2026, I used the language in the I-ring of an edition of Let's Have A Relay (results to be revealed). At [SpecCon](https://www.speccon.org/) in Dublin later that year, I presented a short surprise poem in Anderiva called *Kumi Mande Ka Guppinyinda* 'Ode To A Rock' in [Madeline's](https://www.madelinejameswrites.com/) honour (slides [here](../files/anderiva-speccon-2026.pdf) and video [here](https://www.youtube.com/watch?v=oy6jZHuxrFg)).
